# Generated by Django 3.0.7 on 2020-06-30 18:09

from django.db import migrations


def create_data(apps, schema_editor):
    Clients = apps.get_model('onboarding_form', 'Clients')
    Clients(name="Joy Doe", email="joydoe@email.com",
            phone="09039384352", businessName="Fashion", country="Nigeria").save()


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_form', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
