# Generated by Django 3.0.7 on 2020-07-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_form', '0002_onboarding_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='businessName',
            new_name='business_name',
        ),
    ]
